### ISSUE TITLE
Bundle the Stripe PHP bindings into this module

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/stripe#1]
Since the MIT license is GPL-compatible, this external library should be bunded with the stripe module to make life easier on developers + end-users alike.

**Comment by jenlampton** [comment]
Well, I started working on a PR for this, but then realized this isn't the module I needed. I'm going to switch to webform_stripe, but I'll leave this PR incase this is the direction you want to go in the future :)

**Comment by laryn** [comment]
@jenlampton See [the other comment thread](https://github.com/backdrop-contrib/stripe_api/issues/3) RE: webform_stripe. I'm guessing there's something there that we can continue from, even if we rename it back to webform_stripe.

Bundling the library is a good idea.

**Comment by jenlampton** [comment]
As my first act as co-maintainer I'm going to merge the PR for bundling the library to remove a dependency on libraries module. https://github.com/backdrop-contrib/stripe_api/pull/2 :D
