### ISSUE TITLE
Official release

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/stripe#15]
I'm testing out 1.x-2.x and it's working well, including the webform payment. I think that's ready for an official release, perhaps?

And we should unpublish the old Stripe API project on BackdropCMS.org:
https://backdropcms.org/project/stripe_api

**Comment by stpaultim** [comment]
I'm just testing the 1.x-2.x branch for first time. Just testing this module for the first time. 

I was very confused about the webform integration. There isn't any documentation on it. I will create an issue and PR to add more info to README about use with webform module. At least enough to point a new user in the right direction.

**Comment by laryn** [comment]
It's actually the functionality from [webform_stripe](https://www.drupal.org/project/webform_stripe), which @jenlampton  merged directly into this module to minimize the number of Stripe modules floating around. That might help in terms of documentation?

Noting that there may also be new commits to that project that should be included here...

**Comment by laryn** [comment]
Closing this with the release of `1.x-2.0.0`.
