### ISSUE TITLE
Integrate webform_calculator support?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/stripe#19]
I'm not sure what it would take to integrate support for [Webform Calculator](https://github.com/backdrop-contrib/webform_calculator), but that would be helpful in generating a simple "order form" style webform, where you input quantities on a bunch of fields and then hit "Pay now" at the bottom to pay for it all at once. 

The `formula` webform component (and calculated value) would need to be accessible to the Stripe payment functions.

**Comment by yorkshire-pudding** [comment]
@laryn - did you ever investigate what would be involved in this?

**Comment by laryn** [comment]
@yorkshire-pudding  I don't recall specifics but I think on that project I ended up using the provided hook to do some calculations prior to the call to Stripe:
 - https://github.com/backdrop-contrib/stripe/blob/1.x-2.x/stripe.api.php#L55-L97

**Comment by yorkshire-pudding** [comment]
Thanks @laryn - I can work with that
