### ISSUE TITLE
Allow libraries to be loaded elsewhere

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/stripe#33]
In a few other modules I'm helping to make the bundled libraries essentially optional -- they are there for people who need them, but if libraries are managed separately with Composer (and potentially https://github.com/backdrop-contrib/composer_manager) then this module should not use the bundled version.

Examples:

 - https://github.com/backdrop-contrib/simplesamlphp_auth/issues/37
 - https://github.com/backdrop-contrib/sendgrid_integration/issues/7

**Comment by jenlampton** [comment]
I don't think this is a good idea. Based on the issues we ran into with trying to modify the static class map in other issues this seems like causing issues for the 99% for the 1% that want to do things in ways that are unnecessary. 

Backdrop is its own package manager, so there should be no need to worry about where the libraries are loaded - that's Backdrop's job (or, more importantly, the module's job).  I'd rather focus on the problems that are causing people to think that using composer to manage packages might a good idea - and fix those :)
