### ISSUE TITLE
Payment Unsuccessful TLS error

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/stripe#4]
I was getting an error on my localhost because my encryption was not good enough. 
`Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.`

It appears there is a 2-line fix that will force TLS 1.2 if it is available, see the PR for details.

similar/related issue on d.o:
https://www.drupal.org/node/2832133

**Comment by laryn** [comment]
@jenlampton Is this still needed with the latest release?

**Comment by jenlampton** [comment]
I don't think so, I'm not using this PR anymore.
